attractionsOfCities = {
    'njc':[
            {'chinese_name': '南京夫子庙', 'english_name': 'confucian_temple'},
            {'chinese_name': '南京中山陵', 'english_name': 'sunyatsen_mausoleum'},
            {'chinese_name': '南京明孝陵', 'english_name': 'mingxiaolin_mausoleum'},
            {'chinese_name': '南京牛首山', 'english_name': 'niushoushan'},
            {'chinese_name': '南京大报恩寺', 'english_name': 'dabaoen_temple'},
            {'chinese_name': '南京红山森林动物园', 'english_name': 'hongshan_forest_zoo'},
            {'chinese_name': '南京钟山风景名胜区', 'english_name': 'zhongshan_scenic_area'},
            {'chinese_name': '南京栖霞山', 'english_name': 'qixiashan'},
            {'chinese_name': '南京银杏湖乐园', 'english_name': 'ginkgo_lake_paradise'},
            {'chinese_name': '南京秦淮河', 'english_name': 'qinhuai_river'},
            {'chinese_name': '南京玄武湖', 'english_name': 'xuanwu_lake'},
            {'chinese_name': '南京博物院', 'english_name': 'nanjin_museum'},
            {'chinese_name': '南京方山', 'english_name': 'fangshan'},
            {'chinese_name': '南京明城墙', 'english_name': 'ming_dynasty_city_wall'},
            {'chinese_name': '南京百家湖', 'english_name': 'baijia_lake'},
            {'chinese_name': '南京新街口', 'english_name': 'xinjiekou'},
            {'chinese_name': '南京大屠杀遇难同胞纪念馆', 'english_name': 'nanjing_massacre_memorial_and_museum'},
            {'chinese_name': '南京欢乐谷', 'english_name': 'nanjing_happy_valley'},
            {'chinese_name': '南京眼', 'english_name': 'nanjing_eye'},
            {'chinese_name': '南京老门东', 'english_name': 'laomendong'},
            {'chinese_name': '南京海底世界', 'english_name': 'nanjing_underwater_world'},
            {'chinese_name': '南京瞻园', 'english_name': 'zhanyuan'},
            {'chinese_name': '南京大学鼓楼校区', 'english_name': 'nju_gl'},
            {'chinese_name': '南京林业大学', 'english_name': 'nfu'},
            {'chinese_name': '南京航空航天大学明故宫校区', 'english_name': 'nuaa_mgg'},
            {'chinese_name': '东南大学四牌楼校区', 'english_name': 'seu_spl'},
            {'chinese_name': '南京天印湖', 'english_name': 'tianyin_lake'},
          ]
}